doc: Don't rely on `<nixpkgs>` anymore
We're instead re-importing the given Nixkgs with overlays.

Why re-import? It's because `extend` doesn't play well with some
features from Nixpkgs:

```
nix-repl> (pkgs.extend(f: s: { foobarbaz = "hi"; })).foobarbaz
"hi"

nix-repl> (pkgs.extend(f: s: { foobarbaz = "hi"; })).pkgsCross.aarch64-multiplatform.foobarbaz
error: attribute 'foobarbaz' missing, at (string):1:1
```