release-tools: Eval using `imports` to get the file name
Instead of the following error message:

```
error: The option `mobile.device.info' defined in `<unknown-file>' does not exist.
(use '--show-trace' to show detailed location information)
```

We now get:

```
error: The option `mobile.device.info' defined in `.../mobile-nixos/devices/asus-z00t' does not exist.
(use '--show-trace' to show detailed location information)
```